# Generated by Django 4.2 on 2023-04-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
