# Generated by Django 4.2 on 2023-04-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
