# Generated by Django 4.2 on 2023-04-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайк'},
        ),
    ]
